# Generated by Django 5.2.16 on 2026-07-07 21:31

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_academico', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lapso', models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III')], max_length=5)),
                ('objetivo', models.TextField()),
                ('metodo', models.CharField(max_length=100)),
                ('puntuacion_max', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MaxValueValidator(Decimal('20.00'))])),
                ('activo', models.BooleanField(default=True)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_evaluacion', to='app_academico.aulavirtual')),
            ],
            options={
                'verbose_name': 'Plan de Evaluación',
                'verbose_name_plural': 'Planes de Evaluación',
            },
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('fecha', models.DateField()),
                ('puntuacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('descripcion', models.TextField(blank=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='app_evaluaciones.planevaluacion')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_obtenida', models.DecimalField(decimal_places=2, max_digits=5)),
                ('observacion', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='app_evaluaciones.actividad')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='app_academico.estudiante')),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
                'constraints': [models.UniqueConstraint(fields=('actividad', 'estudiante'), name='unique_calificacion_actividad_estudiante')],
            },
        ),
    ]
