# Generated by Django 5.2.16 on 2026-07-07 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_academico', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='usuario',
            field=models.OneToOneField(limit_choices_to={'rol': 'ESTUDIANTE'}, on_delete=django.db.models.deletion.CASCADE, related_name='estudiante', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matricula',
            name='aula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='app_academico.aulavirtual'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='app_academico.estudiante'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='usuario',
            field=models.OneToOneField(limit_choices_to={'rol': 'PROFESOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='profesor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aulavirtual',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='app_academico.profesor'),
        ),
        migrations.AddConstraint(
            model_name='matricula',
            constraint=models.UniqueConstraint(fields=('estudiante', 'aula'), name='unique_matricula_estudiante_aula'),
        ),
    ]
